[versions]
apacheCommonsText = "1.10.0"
checkstyle = "10.12.1"
cyclonedxPlugin = "1.7.4"
dependencyCheckPlugin = "8.3.1"
dependencyTrackCompanionPlugin = "1.1.0"
fbcontrib = "7.4.3"
findsecbugs = "1.12.0"
jacoco = "0.8.10"
junit = "5.9.3"
junitPlatform = "1.9.3"
pmd = "6.55.0"
postgresql = "42.6.0"
sonarPlugin = "4.3.0.3225"
spotbugs = "4.7.3"
spotbugsPlugin = "5.1.1"

[libraries]
apache-commonsText = { module = "org.apache.commons:commons-text", version.ref = "apacheCommonsText" }
cyclonedx-gradlePlugin = { module = "org.cyclonedx:cyclonedx-gradle-plugin", version.ref = "cyclonedxPlugin" }
dependencyCheck-gradlePlugin = { module = "org.owasp:dependency-check-gradle", version.ref = "dependencyCheckPlugin" }
dependencyTrackCompanion-gradlePlugin = { module = "com.liftric:dependency-track-companion-plugin", version.ref = "dependencyTrackCompanionPlugin" }
findsecbugs = { module = "com.h3xstream.findsecbugs:findsecbugs-plugin", version.ref = "findsecbugs" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit"}
junit-jupiterPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitPlatform"}
postgresql-jdbc = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
sonar-gradlePlugin = { module = "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin", version.ref = "sonarPlugin" }
spotbugs = { module = "com.github.spotbugs:spotbugs", version.ref = "spotbugs"}
spotbugs-gradlePlugin = { module = "com.github.spotbugs.snom:spotbugs-gradle-plugin", version.ref = "spotbugsPlugin"}

[bundles]

[plugins]
dependencyTrackCompanion = { id = "com.liftric.dependency-track-companion-plugin", version.ref = "dependencyTrackCompanionPlugin" }
